//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int ID_BOOK { get; set; }
        public string NameBook { get; set; }
        public string Fio { get; set; }
        public string PublishName { get; set; }
        public decimal Price { get; set; }
        public int Pages { get; set; }
        public System.DateTime DateOfPublishing { get; set; }
        public decimal SalePrice { get; set; }
    }
}
