//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int ID_SALE { get; set; }
        public int ID_BOOK { get; set; }
        public string Login { get; set; }
        public System.DateTime DateOfSale { get; set; }
        public decimal Price { get; set; }
    }
}
